version: "3"
services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: patient-back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:
